source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftECP_Example', :exclusive => true do
  pod "SwiftECP", :path => "../"
end

target 'SwiftECP_Tests', :exclusive => true do
  pod "SwiftECP", :path => "../"

  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '2.0.0-rc.3'
end
