source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'SwiftECP_Example' do
  pod "SwiftECP", :path => "../"

  target 'SwiftECP_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0'
    pod 'Nimble', '~> 7.0'
  end
end
